### ISSUE TITLE
Fix flaky CircleCI tests

### ISSUE THREAD

**Issue by zhuhanming** [Coursemology/coursemology2#4040]
Flaky tests:

```
Course::Duplication::CourseDuplicationService with tenant :instance #duplicate_course when survey question options has attachments duplicates the attachment references but not the attachments

Failure/Error:
  create(:survey_question, :multiple_choice, section: survey.sections.first,
                                             option_traits: [:with_attachment])

ActiveRecord::NotNullViolation:
  PG::NotNullViolation: ERROR:  null value in column "attachment_id" violates not-null constraint
  DETAIL:  Failing row contains (6dbedebf-f804-4a19-8091-7e60b0e5d377, 2, Course::Survey::QuestionOption, null, text.txt, null, 1, 1, 2021-10-04 01:15:24.094205, 2021-10-04 01:15:24.094205).
./spec/services/course/duplication/course_duplication_service_spec.rb:459:in `block (5 levels) in <top (required)>'
./spec/support/bullet.rb:8:in `block in extended'
------------------
--- Caused by: ---
PG::NotNullViolation:
  ERROR:  null value in column "attachment_id" violates not-null constraint
  DETAIL:  Failing row contains (6dbedebf-f804-4a19-8091-7e60b0e5d377, 2, Course::Survey::QuestionOption, null, text.txt, null, 1, 1, 2021-10-04 01:15:24.094205, 2021-10-04 01:15:24.094205).
  ./spec/services/course/duplication/course_duplication_service_spec.rb:459:in `block (5 levels) in <top (required)>'
```

```
Course::Duplication::CourseDuplicationService with tenant :instance #duplicate_course when survey question options has attachments duplicates the question options

Failure/Error:
  create(:survey_question, :multiple_choice, section: survey.sections.first,
                                             option_traits: [:with_attachment])

ActiveRecord::NotNullViolation:
  PG::NotNullViolation: ERROR:  null value in column "attachment_id" violates not-null constraint
  DETAIL:  Failing row contains (a1a7ec90-991d-4428-af73-305d0b3baec2, 4, Course::Survey::QuestionOption, null, text.txt, null, 1, 1, 2021-10-04 01:15:24.380616, 2021-10-04 01:15:24.380616).
./spec/services/course/duplication/course_duplication_service_spec.rb:459:in `block (5 levels) in <top (required)>'
./spec/support/bullet.rb:8:in `block in extended'
------------------
--- Caused by: ---
PG::NotNullViolation:
  ERROR:  null value in column "attachment_id" violates not-null constraint
  DETAIL:  Failing row contains (a1a7ec90-991d-4428-af73-305d0b3baec2, 4, Course::Survey::QuestionOption, null, text.txt, null, 1, 1, 2021-10-04 01:15:24.380616, 2021-10-04 01:15:24.380616).
  ./spec/services/course/duplication/course_duplication_service_spec.rb:459:in `block (5 levels) in <top (required)>'
```

**Comment by zhuhanming** [comment]
Reopening + updated it to cover flaky tests instead.

**Comment by ekowidianto** [comment]
Some tests that failed in CircleCI but not locally are caused by yarn build caching issue which is now solved in #4221

**Comment by zhuhanming** [comment]
Tentatively closed in #4223. Will reopen a new issue if any other flaky tests resurface. Thanks @ekowidianto!

**Comment by ekowidianto** [comment]
Re-opening due to the following flaky tests:

**Backend job error**
Any test that uses wait_for_job, the job would either never end or cant be found in the db in CI. Very hard to debug as this cant be reproduced locally.

- spec/controllers/course/object_duplication_controller_spec.rb
- spec/controllers/course/assessment/assessments_controller_spec.rb
- spec/controllers/course/assessment/submission/submissions_controller_spec.rb
- spec/features/course/duplication_spec.rb
- spec/features/course/assessment/assessment_attempt_spec.rb
- spec/features/course/assessment/answer/forum_post_response_answer_spec.rb
- spec/features/course/assessment/answer/multiple_response_answer_spec.rb
- spec/features/course/assessment/answer/text_response_answer_spec.rb
- spec/features/course/assessment/question/programming_management_spec.rb
- spec/features/course/assessment/submission/autograded_spec.rb
- spec/features/course/assessment/submission/manually_graded_spec.rb
- spec/features/course/assessment/submission/programming_answer_comment_spec.rb
- spec/features/course/assessment/submission/submissions_spec.rb
- spec/models/course/assessment/submission_spec.rb
- spec/services/course/assessment/question/answers_evaluation_service_spec.rb
